version: "3.3"
   
services:
  web:
    build: .
    command: /bin/bash -l -c 'python manage.py makemigrations && 
                              python manage.py migrate && 
                              python script_xlsx_to_db.py &&
                              python manage.py createsuperuser --noinput --username admin --email admin@admin.com &&
                              python manage.py runserver 0:8000'
    volumes:
      - .:/code
    ports:
      - "8000:8000" 